export const API_ENDPOINTS = {
  AUTH_LOGIN: "/api/v1/auth/login",
  AUTH_REFRESH: "/api/v1/auth/refresh",
  CHAT: "/api/v1/chat",
  CUSTOMERS: "/api/v1/customers",
  CUSTOMER_LTV: (id: string) => `/api/v1/customers/${id}/ltv`,
  CUSTOMERS_TOP: "/api/v1/customers/top",
  CUSTOMERS_CHURN: "/api/v1/customers/churn",
  CAMPAIGNS: "/api/v1/campaigns",
  UPLOADS: "/api/v1/uploads",
  UPLOAD: (id: string) => `/api/v1/uploads/${id}`,
  ANALYTICS: "/api/v1/analytics",
  AUDIT: "/api/v1/audit",
  SETTINGS_PROFILE: "/api/v1/settings/profile",
  SETTINGS_TEAM: "/api/v1/settings/team",
  SETTINGS_TEAM_MEMBER: (id: string) => `/api/v1/settings/team/${id}`,
  SETTINGS_INTEGRATIONS: "/api/v1/settings/integrations",
} as const;
